#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "Tutanota"
name = "tutanota"
description.en = "Email service with a strong focus on security and privacy"
description.fr = "Email service with a strong focus on security and privacy"

version = "3.118.4~ynh1"

maintainers = [""]

[upstream]
license = "GPL-3.0"
website = "https://tutanota.com"
admindoc = "https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md"
code = "https://github.com/tutao/tutanota/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/tutao/tutanota/archive/refs/tags/tutanota-release-3.118.4.tar.gz"
        sha256 = "65d7c1ba44530556af849288b6f111da4e062960fbb86096c3b83620abb34933"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
